name: Check for changes and commit every 12 hours

on:
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:

jobs:
  check_for_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: "actions/checkout@v3"

      - name: Read current workflow env
        id: get_current_env
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.env.workflow

      - name: Echo current commit
        id: set_commit_output
        run: echo "::set-output name=current_commit::$(echo ${{ steps.get_current_env.outputs.content }} | cut -d'=' -f2)"

      - name: Get latest TWIR commit
        id: get_latest_commit
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/commits
          owner: rust-lang
          repo: this-week-in-rust
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make changes
        if: ${{ steps.set_commit_output.outputs.current_commit }} != ${{ fromJson(steps.get_latest_commit.outputs.data).sha }}
        run: |
          touch .env.wokrflow
          echo TWIR_COMMIT=${{ fromJson(steps.get_latest_commit.outputs.data).sha }} >> .env.wokrflow

      - name: Push changes
        if: ${{ steps.set_commit_output.outputs.current_commit }} != ${{ fromJson(steps.get_latest_commit.outputs.data).sha }}
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          branch: ${{ github.ref }}
